### ISSUE TITLE
About spaced string argument support

### ISSUE THREAD

**Issue by dytroInc** [monun/kommand#1]
혹시 띄어쓰기를 포함시킬 수 있는 문자열 argument를 지원하나요?

제가 놓치는 부분이 있을 수도 있는데 지원하는 거 같지 않아서 물어보는 겁니다.

**Comment by monun** [comment]
아니요 원리적으로 지원하지 않습니다.

underbar를 이용하세요

저도 기능 추가를 고민했는데 얻는것보다 잃는게 더 많더라구요

**Comment by dytroInc** [comment]
그렇군요, 약간 아쉽네요. 그래도 늦게까지 답변해주셔서 감사합니다.
