### ISSUE TITLE
여러 개의 argument를 어떻게 구분해서 받나요?

### ISSUE THREAD

**Issue by MisileLab** [monun/kommand#11]
```kotlin
then("add") {
    then("x" to int()) {
        then("y" to int()) {
            then("z" to int()) {
                executes { context ->
                    val x: Int by context // x position argument
                  	val y: Int by context // y position argument
					val z: Int by context // z position argument
                    // Code
                    }
                }
            }
        }
    }
}
```
지금 이 상태에서 x와 y, z를 따로 변수로 지정해야 하는 상황입니다. 어떻게 해야할까요?

**Comment by qogusdn1017** [comment]
private function을 따로 만들어서 x, y, z 변수에 대한 값들을 한번에 지정 가능하게 하실 수는 없을까요?

그럼 코드 줄도 줄텐데

**Comment by MisileLab** [comment]
> private function을 따로 만들어서 x, y, z 변수에 대한 값들을 한번에 지정 가능하게 하실 수는 없을까요?
> 
> 그럼 코드 줄도 줄텐데

제가 kotlin 뉴비라 예시를 보여줄 수 있나요?

**Comment by qogusdn1017** [comment]
> > private function을 따로 만들어서 x, y, z 변수에 대한 값들을 한번에 지정 가능하게 하실 수는 없을까요?
> > 그럼 코드 줄도 줄텐데
> 
> 제가 kotlin 뉴비라 예시를 보여줄 수 있나요?

보여주신 코드 구조가 정상작동할지는 모르겠네요

일단 저는 function 방식으로 주어진 값을 이용해 특정 행동을 취합니당

[참고](https://github.com/qogusdn1017/ChunkErrorPlugin/blob/6145efdcd62c2bc3c46d405721da7407d9bb7a0c/src/main/kotlin/com/baehyeonwoo/chunkerror/ChunkErrorKommand.kt#L23)
