### ISSUE TITLE
Aliaes 로 등록된 명령어에서 기본 executes 가 작동하지 않음.

### ISSUE THREAD

**Issue by StayCake** [monun/kommand#13]
![image](https://user-images.githubusercontent.com/36215887/128038360-8af6c765-48dc-4e1d-a138-345e64239cb1.png)
![image](https://user-images.githubusercontent.com/36215887/128038447-84d173f4-34a1-4d79-9fcc-72f37b8939ed.png)
![image](https://user-images.githubusercontent.com/36215887/128038491-9ad3a9ca-7577-4f5b-b474-735fbf837f8f.png)

**Comment by dytroInc** [comment]
kommand 수정할 땐 reload 보단 restart을 해야지 되는 걸로 기억합니다.

**Comment by StayCake** [comment]
> kommand 수정할 땐 reload 보단 restart을 해야지 되는 걸로 기억합니다.

해당 조치 이후에도 동일 증상입니다.

**Comment by qogusdn1017** [comment]
> > kommand 수정할 땐 reload 보단 restart을 해야지 되는 걸로 기억합니다.
> 
> 해당 조치 이후에도 동일 증상입니다.

형 지금은 해결됨?

**Comment by qogusdn1017** [comment]
같은 현상 확인됨. Argument없이 Native로만 실행할 시 오류가 발생.

**Comment by NamuTree0345** [comment]
저는 기본 이름으로 실행하면 없는 명령어라고 나오네요.

**Comment by monun** [comment]
최신 버전에서도 동일한 증상이 나오나요

**Comment by StayCake** [comment]
3.1.1 기준 이상 없습니다 이슈 닫습니다
