### ISSUE TITLE
!질문 아래와 같은 상황이면 어떻게 처리하면 될까요?

### ISSUE THREAD

**Issue by donghune** [monun/kommand#2]
/item modify display [value]
/item modify display 초보자의 검

kommand가 공백을 기준으로 argument 하나씩 배정이 되어 체크를 하는것으로 알고 있는데
현재로서 방법은 특정기호로 구분지어 replace 하는 방법이 있습니다.

별도의 방법이 있거나 ' 또는 " 으로 구분할 수 있는 방법이 있을까요?

/item modify display "초보자의 검"
/item modify display '초보자의 검'

**Comment by monun** [comment]
저도 이 문제 때문에 고민이 깊습니다

우선은 언더바를 이용해 공백으로 문자열 치환을 하셔야 할듯 합니다

**Comment by patrick-choe** [comment]
2.0 출시로 `string(QUOTABLE_PHRASE)` 사용이 가능합니다.

사용 예제: https://github.com/monun/kommand/blob/master/kommand-debug/src/main/kotlin/io/github/monun/kommand/plugin/KommandPlugin.kt#L69-L76

**Comment by qogusdn1017** [comment]
이슈 닫아주세요.
