### ISSUE TITLE
mavenCentral repo

### ISSUE THREAD

**Issue by shs3182ym** [monun/kommand#25]
현재 2.8.1 (2021-12-31) 넘는 버전이 repo에 없어서 수동으로 빌드해야합니다.
mavenCentral repo가 방치 상태인가요?

**Comment by monun** [comment]
왜 이럴까요.. close-publish까지 완료했는데 업데이트가 안되네요

**Comment by monun** [comment]
원인을 찾았습니다.

구현체 저장소의 이름이 kommand 에서 kommand-core 로 변경되었습니다.
