### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by eudhs29** [monun/kommand#3]
지금 1.17 이후부터 JDK 16으로 왔는데, 혹시 "io.papermc.paper:paper-api:+" 이거 쓰셔도 괜찮을거 같습니다, 1.17을 지원하고 JDK 16 깔고 테스트 해봤는데 잘 되더라구요, 나중에 만드실 때 고려해보셔도 괜찮을 거 같습니다

**Comment by monun** [comment]
감사합니다

**Comment by eudhs29** [comment]
감사합니다 사랑해요 별님

**Comment by eudhs29** [comment]
혹시나 자료을 필요로 하실까봐 링크까지 첨부해드릴게요. 그냥 페이퍼 레포지토리 입니다 `https://github.com/PaperMC/Paper`
