### ISSUE TITLE
location 변수의 pitch와 yaw가 뒤바뀜

### ISSUE THREAD

**Issue by jung27** [monun/kommand#35]
location이 실제 위치의 pitch와 yaw를 바꾼 위치입니다.

`kommand.register("commandName"){
    executes{
        player.sendMessage("$location\n${player.location}")
    }
}`

![image](https://user-images.githubusercontent.com/91370082/209462126-9cc961f9-19f5-4b80-8188-49c696c76d6b.png)

**Comment by jung27** [comment]
#36

**Comment by monun** [comment]
오..

**Comment by jung27** [comment]
감사합니당
