### ISSUE TITLE
Kommand 사용방법에 대한 자료가 부족합니다.

### ISSUE THREAD

**Issue by myoun** [monun/kommand#6]
현재 Kommand 사용 방법에 대한 자료가 부족합니다.
Kommand를 사용하고 싶지만, 이에 대한 자료가 거의 없어서 공식 위키같은 안내서가 필요합니다.

**Comment by qogusdn1017** [comment]
비공식 제작중입니다
https://monun.me/

**Comment by myoun** [comment]
@qogusdn1017 
제작 완료되면 알려주실수 있으신가요?

**Comment by qogusdn1017** [comment]
현재 각별(monun)님이 1.17 업데이트 이후 CommandAPI를 이용해 ReWrite작업중이십니다! 다른 브랜치에서 확인 가능합니다

따라서 ReWrite 작업이 끝나고 많이 안정되면 시간날때 팀원과 작업할 것 같습니다

~~문서를 너무 믿지 마세요 유사개발자가 작성한겁니다~~

**Comment by qogusdn1017** [comment]
이제 이슈를 닫아도 되지 않을까요?

**Comment by myoun** [comment]
자료가 부족한건 여전합니다
