### ISSUE TITLE
1.17.1 에서 정상작동 하지 않습니다.

### ISSUE THREAD

**Issue by StayCake** [monun/kommand#8]
예시로 제공된 내용을 그대로 테스트를 진행하였는데도 정상적인 작동을 하지 않습니다.
오류 로그로 보아 변경된 1.17.1과 1.17의 NMS 차이로 추정됩니다.
![image](https://user-images.githubusercontent.com/36215887/125180277-2eb8bb00-e233-11eb-9de4-a5b229b87a2c.png)

**Comment by neonny0** [comment]
"정적 이니셜라이저에서 예기치 않은 예외가 발생했음을 알립니다. ExceptionInInitializerError정적 이니셜라이저 또는 정적 변수에 대한 이니셜라이저를 평가하는 동안 예외가 발생했음을 나타내기 위해 An 이 발생합니다.
릴리스 1.4부터 이 예외는 범용 예외 연결 메커니즘을 준수하도록 개조되었습니다. 생성 시 제공되고 getException()메서드 를 통해 액세스할 수 있는 "저장된 throw 가능 개체" 는 이제 원인으로 알려져 있으며 Throwable.getCause() 앞서 언급한 "레거시 메서드"뿐만 아니라 메서드 를 통해 액세스할 수 있습니다 ." 이라네요, 문서을 읽어보니 이니셜라이저에서 예기치 못한 오류가 발생해서 그렇것 같네요

**Comment by monun** [comment]
1.17.1 아직 미지원이에용..

**Comment by monun** [comment]
이제 지원합니다.
2.0.0 버전으로 테스트해보세요
